export class PlayerDto {
  id: string;
  externalId: string;
  tenantId: string | null;
  affiliateId: string | null;
  name: string | null;
  email: string;
  country: string | null;
  language: string | null;
  date: Date | null;
  phoneCountryCode: string | null;
  phone: string | null;
  balance: number;
  birthDate: Date | null;
  firstDepositDate: Date | null;
  firstDepositValue: number | null;
  lastDepositDate: Date | null;
  lastDepositValue: number | null;
  totalDepositCount: number | null;
  totalDepositValue: number | null;
  lastWithdrawalDate: Date | null;
  lastWithdrawalValue: number | null;
  totalWithdrawalCount: number | null;
  totalWithdrawalValue: number | null;
  mostFrequentBetPair: string | null;
  mostFrequentViewedPair: string | null;
  lastLoginDate: Date | null;
  lastAccessDate: Date | null;
  playerStatus: String;
  createdAt: Date;
  updatedAt: Date;
}
